services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "start"]

  backend:
    build:
      context: ./backend
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: app_db

  db:
    image: mysql:8.0
    platform: linux/arm64
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db-volume:
